[package]
name = "substreams"
version = "0.1.0"
description = "Substreams base library"
edition = "2018"

[dependencies]
prost = { version = "0.6" }
prost-types = "0.6"
hex = "0.4.3"
num-bigint = "0.4"
